baseURL = "https://timely-sunshine-a06224.netlify.app/"
languageCode = "nl-nl"
title = "Jayco Research Tool"

[menu]

  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

  [[menu.main]]
    name   = "Landenrisico’s"
    url    = "/landen/"
    weight = 2

  [[menu.main]]
    name   = "Sectorrisico’s"
    url    = "/sectoren/"
    weight = 3

  [[menu.main]]
    name   = "Standaardteksten"
    url    = "/standaard-teksten/"
    weight = 4

  [[menu.main]]
    name   = "Admin"
    url    = "/admin/"
    weight = 5
